# annotations:
    # screwdriver.cd/restrictPR: fork
jobs:
  blocked-job:
    image: node:lts
    requires: [~commit, ~pr]
    steps:
      - main: sleep 5
    
  blocked-job-1:
    requires: [~blocked-job]
    image: node:lts
    blockedBy: [~blocked-job]
    steps:
      - main: echo "hello"
  blocked-job-2:
    requires: [~commit, ~pr]
    image: node:lts
    blockedBy: [~blocked-job]
    steps:
      - main: echo "hello world"
  sample-job:
    requires: [~pr,~commit]
    image: node:lts
    steps:
      - echo-hello: echo "hello world 4"
      - wait: sleep 10m
  invalid-job:
    requires: [~pr,~commit]
    image: node:abc
    steps:
      - echo-hello: echo "hello world 4"
      - wait: sleep 10m

  large-image:
   requires: [~pr,~commit]
   image: tensorflow/tensorflow:latest-gpu
   steps:
      - echo-hello: echo "hello world 4"

  close-job:
    requires: [~pr-closed]
    image: node:lts
    environment:
      USER_SHELL_BIN: bash
    steps:
      - echo-hello: echo "pr closed workflow"
      - check-meta: |
          meta get sd.pr
  job-A:
      requires: [~pr, ~pr-closed]
      image: node:lts
      environment:
        USER_SHELL_BIN: bash
      steps:
        - check-meta: |
            echo $SD_PULL_REQUEST
            meta get sd.pr    
  job-B:
      requires: [~pr:release, ~pr-closed:release]
      image: node:lts
      steps:
        - check-meta: meta get sd
  
