jobs:
  sample-job:
    requires: [~pr,~commit]
    image: node:lts
    steps:
      - echo-hello: echo "hello world 3"
  close-job:
    requires: [~prclosed]
    image: node:lts
    steps:
      - echo-hello: echo "pr closed"
  
