jobs:
  sample-job:
    requires: [~pr,~commit]
    image: node:lts
    steps:
      - echo-hello: echo "hello world 1"
  close-job:
    requires: [~pr-closed]
    image: node:lts
    steps:
      - echo-hello: echo "pr closed test"
  
