jobs:
  sample-job:
    requires: [~pr,~commit]
    image: node:lts
    steps:
      - echo-hello: echo "hello world 4"
  close-job:
    requires: [~pr-closed]
    image: node:lts
    steps:
      - echo-hello: echo "pr closed workflow"
      - check-meta: meta get sd
  
