jobs:
  sample-job:
    requires: [~pr,~commit]
    image: node:lts
    steps:
      - echo-hello: echo "hello world 4"
  close-job:
    requires: [~pr-closed]
    image: node:lts
    environment:
      USER_SHELL_BIN: bash
    steps:
      - echo-hello: echo "pr closed workflow"
      - check-meta: |
          meta get sd.pr
  job-A:
      requires: [~pr, ~pr-closed]
      image: node:lts
      environment:
        USER_SHELL_BIN: bash
      steps:
        - check-meta: |
            echo $SD_PULL_REQUEST
            meta get sd
            meta get sd.pr
  
